# Generated by Django 6.1.1 on 2026-10-02 12:23

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('leads', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followup_id', models.CharField(editable=False, help_text='Auto-generated follow-up ID', max_length=20, unique=True)),
                ('followup_date', models.DateField(default=django.utils.timezone.now)),
                ('followup_time', models.TimeField(blank=True, null=True)),
                ('followup_type', models.CharField(choices=[('Call', 'Call'), ('Email', 'Email'), ('Meeting', 'Meeting'), ('Other', 'Other')], default='Call', max_length=20)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20)),
                ('outcome', models.TextField(blank=True, help_text='Recorded outcome upon completion')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followups', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='followups', to='customers.customer')),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='followups', to='leads.lead')),
            ],
            options={
                'ordering': ['followup_date', 'followup_time'],
                'indexes': [models.Index(fields=['followup_id'], name='followups_f_followu_0d7eb4_idx'), models.Index(fields=['followup_date'], name='followups_f_followu_4b99c5_idx'), models.Index(fields=['status'], name='followups_f_status_257d35_idx'), models.Index(fields=['assigned_to', 'status'], name='followups_f_assigne_71f52a_idx')],
            },
        ),
    ]
