# Generated by Django 6.1.1 on 2026-10-02 12:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead_id', models.CharField(editable=False, help_text='Auto-generated unique lead identifier', max_length=20, unique=True)),
                ('full_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('company', models.CharField(blank=True, max_length=150)),
                ('source', models.CharField(choices=[('Website', 'Website'), ('Instagram', 'Instagram'), ('Facebook', 'Facebook'), ('Referral', 'Referral'), ('Other', 'Other')], default='Website', max_length=50)),
                ('interested_product', models.CharField(blank=True, max_length=150)),
                ('estimated_deal_value', models.DecimalField(decimal_places=2, default=0.0, help_text='Estimated deal value in INR (₹)', max_digits=12)),
                ('status', models.CharField(choices=[('New', 'New'), ('Contacted', 'Contacted'), ('Interested', 'Interested'), ('Qualified', 'Qualified'), ('Converted', 'Converted'), ('Lost', 'Lost')], default='New', max_length=20)),
                ('priority', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='Medium', max_length=20)),
                ('next_followup_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('lost_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to=settings.AUTH_USER_MODEL)),
                ('converted_customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='converted_from_leads', to='customers.customer')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['lead_id'], name='leads_lead_lead_id_c7b906_idx'), models.Index(fields=['status'], name='leads_lead_status_e23abe_idx'), models.Index(fields=['priority'], name='leads_lead_priorit_ddce28_idx'), models.Index(fields=['source'], name='leads_lead_source_200868_idx'), models.Index(fields=['-created_at'], name='leads_lead_created_921505_idx')],
            },
        ),
    ]
