services:
  - type: web
    name: smartcrm
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn smartcrm.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "*"
      - key: CSRF_TRUSTED_ORIGINS
        value: "https://*.onrender.com"
      - key: SECRET_KEY
        generateValue: true
