# Generated by Django 6.1.1 on 2026-10-02 12:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('leads', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deal_id', models.CharField(editable=False, help_text='Auto-generated unique deal identifier', max_length=20, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('deal_value', models.DecimalField(decimal_places=2, default=0.0, help_text='Deal value in INR (₹)', max_digits=12)),
                ('stage', models.CharField(choices=[('New', 'New'), ('Proposal', 'Proposal'), ('Negotiation', 'Negotiation'), ('Won', 'Won'), ('Lost', 'Lost')], default='New', max_length=20)),
                ('expected_closing_date', models.DateField()),
                ('actual_closing_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deals', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deals', to='customers.customer')),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deals', to='leads.lead')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['deal_id'], name='sales_deal_deal_id_f5b7cc_idx'), models.Index(fields=['stage'], name='sales_deal_stage_7c0d7f_idx'), models.Index(fields=['expected_closing_date'], name='sales_deal_expecte_eccd6e_idx'), models.Index(fields=['assigned_to', 'stage'], name='sales_deal_assigne_f6b481_idx')],
            },
        ),
    ]
